/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	AuthenticateRegistrationIdPost(http.ResponseWriter, *http.Request)
	BboxesGet(http.ResponseWriter, *http.Request)
	ConfigsBboxAssociatePost(http.ResponseWriter, *http.Request)
	ConfigsBboxDelete(http.ResponseWriter, *http.Request)
	ConfigsBboxGet(http.ResponseWriter, *http.Request)
	ConfigsBboxPost(http.ResponseWriter, *http.Request)
	ConfigsBboxPut(http.ResponseWriter, *http.Request)
	ConfigsBboxRegisterPost(http.ResponseWriter, *http.Request)
	HivesDelete(http.ResponseWriter, *http.Request)
	HivesGet(http.ResponseWriter, *http.Request)
	HivesPost(http.ResponseWriter, *http.Request)
	HivesPut(http.ResponseWriter, *http.Request)
	LoginPost(http.ResponseWriter, *http.Request)
	// Deprecated
	ScaleGet(http.ResponseWriter, *http.Request)
	ScaleGetV2(http.ResponseWriter, *http.Request)
	ScalePost(http.ResponseWriter, *http.Request)
	ScalePostV2(http.ResponseWriter, *http.Request)
	StandsDelete(http.ResponseWriter, *http.Request)
	StandsGet(http.ResponseWriter, *http.Request)
	StandsPost(http.ResponseWriter, *http.Request)
	StandsPut(http.ResponseWriter, *http.Request)
	TelemetryPost(http.ResponseWriter, *http.Request)
	TemperatureGet(http.ResponseWriter, *http.Request)
	TemperaturePost(http.ResponseWriter, *http.Request)
	UserPost(http.ResponseWriter, *http.Request)
	VarroaScanGet(http.ResponseWriter, *http.Request)
	VarroaScanImagePost(http.ResponseWriter, *http.Request)
	VarroaScanPost(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	AuthenticateRegistrationIdPost(context.Context, RegistrationId) (ImplResponse, error)
	BboxesGet(context.Context) (ImplResponse, error)
	ConfigsBboxAssociatePost(context.Context, string, string, int64) (ImplResponse, error)
	ConfigsBboxDelete(context.Context, string, string, string, int64) (ImplResponse, error)
	ConfigsBboxGet(context.Context, string, string, string, int64) (ImplResponse, error)
	ConfigsBboxPost(context.Context, string, string, int64, Bbox) (ImplResponse, error)
	ConfigsBboxPut(context.Context, string, string, string, int64, Bbox) (ImplResponse, error)
	ConfigsBboxRegisterPost(context.Context, string, int64, Bbox) (ImplResponse, error)
	HivesDelete(context.Context, string, string, string, int64) (ImplResponse, error)
	HivesGet(context.Context, int64, int64, string, int64) (ImplResponse, error)
	HivesPost(context.Context, string, string, int64, Hive) (ImplResponse, error)
	HivesPut(context.Context, string, string, int64, Hive) (ImplResponse, error)
	LoginPost(context.Context, string, string) (ImplResponse, error)
	// Deprecated
	ScaleGet(context.Context, string, int64, int64, string, string) (ImplResponse, error)
	ScaleGetV2(context.Context, int64, int64, string, string, string, string, int64) (ImplResponse, error)
	ScalePost(context.Context, string, string, string, int64, Weight) (ImplResponse, error)
	ScalePostV2(context.Context, string, int64, ScaleV2) (ImplResponse, error)
	StandsDelete(context.Context, string, string, string, int64) (ImplResponse, error)
	StandsGet(context.Context, string, int64, int64, string, string, int64) (ImplResponse, error)
	StandsPost(context.Context, string, string, int64, Stand) (ImplResponse, error)
	StandsPut(context.Context, string, string, int64, Stand) (ImplResponse, error)
	TelemetryPost(context.Context, string, int64, TelemetryValues) (ImplResponse, error)
	TemperatureGet(context.Context, string, string, int64, int64, string, int64) (ImplResponse, error)
	TemperaturePost(context.Context, int64, Temperature) (ImplResponse, error)
	UserPost(context.Context, User) (ImplResponse, error)
	VarroaScanGet(context.Context, string, string, string, int64, string, int64, int64) (ImplResponse, error)
	VarroaScanImagePost(context.Context, string, string, int64, string, int64, string) (ImplResponse, error)
	VarroaScanPost(context.Context, int64, VarroaScan) (ImplResponse, error)
}
