/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"encoding/json"
)



type Weight struct {

	// bhiveId to identify the data source.
	BhiveId string `json:"bhiveId,omitempty"`

	// actual measurement of weight
	Weight float32 `json:"weight,omitempty"`

	// timestamp of the measurement on one second precision
	Epoch int64 `json:"epoch,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *Weight) UnmarshalJSON(data []byte) error {

	type Alias Weight // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertWeightRequired checks if the required fields are not zero-ed
func AssertWeightRequired(obj Weight) error {
	return nil
}

// AssertWeightConstraints checks if the values respects the defined constraints
func AssertWeightConstraints(obj Weight) error {
	return nil
}
