/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"encoding/json"
)



type ScaleV2Response struct {

	// HTTP response code. Used for internal purposes, will be let out at the API level.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`

	// The measurement responses
	Values []ScaleV2 `json:"values,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *ScaleV2Response) UnmarshalJSON(data []byte) error {

	type Alias ScaleV2Response // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertScaleV2ResponseRequired checks if the required fields are not zero-ed
func AssertScaleV2ResponseRequired(obj ScaleV2Response) error {
	for _, el := range obj.Values {
		if err := AssertScaleV2Required(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertScaleV2ResponseConstraints checks if the values respects the defined constraints
func AssertScaleV2ResponseConstraints(obj ScaleV2Response) error {
	return nil
}
