/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"encoding/json"
)



type RegistrationId struct {

	// Registration ID, in the form of the unique identifier
	RegistrationId string `json:"registrationId"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *RegistrationId) UnmarshalJSON(data []byte) error {

	type Alias RegistrationId // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertRegistrationIdRequired checks if the required fields are not zero-ed
func AssertRegistrationIdRequired(obj RegistrationId) error {
	elements := map[string]interface{}{
		"registrationId": obj.RegistrationId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRegistrationIdConstraints checks if the values respects the defined constraints
func AssertRegistrationIdConstraints(obj RegistrationId) error {
	return nil
}
