/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"encoding/json"
)



type LoginPostResponse struct {

	// HTTP response code.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`

	// cookie that is returned as a cookie to the browser
	Token string `json:"token,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *LoginPostResponse) UnmarshalJSON(data []byte) error {

	type Alias LoginPostResponse // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertLoginPostResponseRequired checks if the required fields are not zero-ed
func AssertLoginPostResponseRequired(obj LoginPostResponse) error {
	return nil
}

// AssertLoginPostResponseConstraints checks if the values respects the defined constraints
func AssertLoginPostResponseConstraints(obj LoginPostResponse) error {
	return nil
}
