/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetBboxResponse struct {

	Bboxes []Bbox `json:"bboxes,omitempty"`

	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`
}

// AssertGetBboxResponseRequired checks if the required fields are not zero-ed
func AssertGetBboxResponseRequired(obj GetBboxResponse) error {
	for _, el := range obj.Bboxes {
		if err := AssertBboxRequired(el); err != nil {
			return err
		}
	}
	return nil
}
