/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type VarroaScanResponse struct {

	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpReponseCode int32 `json:"httpReponseCode,omitempty"`

	VarroaScans []VarroaScan `json:"varroaScans,omitempty"`
}

// AssertVarroaScanResponseRequired checks if the required fields are not zero-ed
func AssertVarroaScanResponseRequired(obj VarroaScanResponse) error {
	for _, el := range obj.VarroaScans {
		if err := AssertVarroaScanRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseVarroaScanResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of VarroaScanResponse (e.g. [][]VarroaScanResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseVarroaScanResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aVarroaScanResponse, ok := obj.(VarroaScanResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertVarroaScanResponseRequired(aVarroaScanResponse)
	})
}
