/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"encoding/json"
)



type GetHivesResponse struct {

	Hives []Hive `json:"hives,omitempty"`

	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *GetHivesResponse) UnmarshalJSON(data []byte) error {

	type Alias GetHivesResponse // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertGetHivesResponseRequired checks if the required fields are not zero-ed
func AssertGetHivesResponseRequired(obj GetHivesResponse) error {
	for _, el := range obj.Hives {
		if err := AssertHiveRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetHivesResponseConstraints checks if the values respects the defined constraints
func AssertGetHivesResponseConstraints(obj GetHivesResponse) error {
	return nil
}
