/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostBboxResponse struct {

	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`

	Bbox Bbox `json:"bbox,omitempty"`
}

// AssertPostBboxResponseRequired checks if the required fields are not zero-ed
func AssertPostBboxResponseRequired(obj PostBboxResponse) error {
	if err := AssertBboxRequired(obj.Bbox); err != nil {
		return err
	}
	return nil
}

// AssertRecursePostBboxResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PostBboxResponse (e.g. [][]PostBboxResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePostBboxResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPostBboxResponse, ok := obj.(PostBboxResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPostBboxResponseRequired(aPostBboxResponse)
	})
}
