/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Alerts struct {

	// Various alerts a bee hive can have.
	AlertType string `json:"alertType"`
}

// AssertAlertsRequired checks if the required fields are not zero-ed
func AssertAlertsRequired(obj Alerts) error {
	elements := map[string]interface{}{
		"alertType": obj.AlertType,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseAlertsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Alerts (e.g. [][]Alerts), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseAlertsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aAlerts, ok := obj.(Alerts)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertAlertsRequired(aAlerts)
	})
}
