/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TelemetryResponse struct {

	// HTTP response code. Used for internal purposes, will be let out at the API level.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`

	// The measurement responses
	Values []Telemetry `json:"values,omitempty"`
}

// AssertTelemetryResponseRequired checks if the required fields are not zero-ed
func AssertTelemetryResponseRequired(obj TelemetryResponse) error {
	for _, el := range obj.Values {
		if err := AssertTelemetryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseTelemetryResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TelemetryResponse (e.g. [][]TelemetryResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTelemetryResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTelemetryResponse, ok := obj.(TelemetryResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTelemetryResponseRequired(aTelemetryResponse)
	})
}
