/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BboxBhiveInner struct {

	// The ID of a beehive. Is unique for that user.
	BhiveId string `json:"bhiveId,omitempty"`
}

// AssertBboxBhiveInnerRequired checks if the required fields are not zero-ed
func AssertBboxBhiveInnerRequired(obj BboxBhiveInner) error {
	return nil
}

// AssertRecurseBboxBhiveInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of BboxBhiveInner (e.g. [][]BboxBhiveInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseBboxBhiveInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aBboxBhiveInner, ok := obj.(BboxBhiveInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertBboxBhiveInnerRequired(aBboxBhiveInner)
	})
}
