/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi


import (
	"encoding/json"
)



type TelemetryResponse struct {

	// HTTP response code. Used for internal purposes, will be let out at the API level.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`

	// The measurement responses
	Values []Telemetry `json:"values,omitempty"`
}

// UnmarshalJSON sets *m to a copy of data while respecting defaults if specified.
func (m *TelemetryResponse) UnmarshalJSON(data []byte) error {

	type Alias TelemetryResponse // To avoid infinite recursion
    return json.Unmarshal(data, (*Alias)(m))
}

// AssertTelemetryResponseRequired checks if the required fields are not zero-ed
func AssertTelemetryResponseRequired(obj TelemetryResponse) error {
	for _, el := range obj.Values {
		if err := AssertTelemetryRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertTelemetryResponseConstraints checks if the values respects the defined constraints
func AssertTelemetryResponseConstraints(obj TelemetryResponse) error {
	return nil
}
