/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetBboxResponse struct {

	Stands []Bbox `json:"stands,omitempty"`

	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`
}

// AssertGetBboxResponseRequired checks if the required fields are not zero-ed
func AssertGetBboxResponseRequired(obj GetBboxResponse) error {
	for _, el := range obj.Stands {
		if err := AssertBboxRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetBboxResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetBboxResponse (e.g. [][]GetBboxResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetBboxResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetBboxResponse, ok := obj.(GetBboxResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetBboxResponseRequired(aGetBboxResponse)
	})
}
