/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetHivesResponse struct {

	Hives []Hive `json:"hives,omitempty"`

	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`
}

// AssertGetHivesResponseRequired checks if the required fields are not zero-ed
func AssertGetHivesResponseRequired(obj GetHivesResponse) error {
	for _, el := range obj.Hives {
		if err := AssertHiveRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetHivesResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetHivesResponse (e.g. [][]GetHivesResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetHivesResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetHivesResponse, ok := obj.(GetHivesResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetHivesResponseRequired(aGetHivesResponse)
	})
}
