/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginPostResponse struct {

	// HTTP response code.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`

	// cookie that is returned as a cookie to the browser
	Cookie string `json:"cookie,omitempty"`
}

// AssertLoginPostResponseRequired checks if the required fields are not zero-ed
func AssertLoginPostResponseRequired(obj LoginPostResponse) error {
	return nil
}

// AssertRecurseLoginPostResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LoginPostResponse (e.g. [][]LoginPostResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLoginPostResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLoginPostResponse, ok := obj.(LoginPostResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLoginPostResponseRequired(aLoginPostResponse)
	})
}
