/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PostHivesResponse struct {

	// HTTP response code. Used for internal purposes, will be sent out at the API.
	HttpResponseCode int32 `json:"httpResponseCode,omitempty"`

	Hive Hive `json:"hive,omitempty"`
}

// AssertPostHivesResponseRequired checks if the required fields are not zero-ed
func AssertPostHivesResponseRequired(obj PostHivesResponse) error {
	if err := AssertHiveRequired(obj.Hive); err != nil {
		return err
	}
	return nil
}

// AssertRecursePostHivesResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PostHivesResponse (e.g. [][]PostHivesResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePostHivesResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPostHivesResponse, ok := obj.(PostHivesResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPostHivesResponseRequired(aPostHivesResponse)
	})
}
