/*
 * Queensaver API
 *
 * Queensaver API to send in sensor data and retrieve it. It's also used for user management.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type ScaleV2 struct {

	// The mac address of the scale
	MacAddress string `json:"macAddress,omitempty"`

	// actual measurement of weight
	Weight float32 `json:"weight,omitempty"`

	// timestamp of the measurement on one second precision
	Epoch int64 `json:"epoch,omitempty"`
}

// AssertScaleV2Required checks if the required fields are not zero-ed
func AssertScaleV2Required(obj ScaleV2) error {
	return nil
}
