/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Alerts { 
    /**
     * Various alerts a bee hive can have.
     */
    alertType: Alerts.AlertTypeEnum;
}
export namespace Alerts {
    export type AlertTypeEnum = 'VarroaHigh' | 'WeightLow' | 'QueenLess';
    export const AlertTypeEnum = {
        VarroaHigh: 'VarroaHigh' as AlertTypeEnum,
        WeightLow: 'WeightLow' as AlertTypeEnum,
        QueenLess: 'QueenLess' as AlertTypeEnum
    };
}


