/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BboxBhiveInner } from './bboxBhiveInner';


export interface Bbox { 
    /**
     * ID of the object. The ID is usually determined by the DBMS.
     */
    bboxId?: number;
    /**
     * A cron type of description of when the sensore measurements are supposed to be done.
     */
    schedule?: string;
    bhive?: Array<BboxBhiveInner>;
}

