/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LoginPostResponse { 
    /**
     * HTTP response code.
     */
    httpResponseCode?: number;
    /**
     * cookie that is returned as a cookie to the browser
     */
    token?: string;
}

