/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelemetryInner { 
    /**
     * The mac address of the scale
     */
    macAddress?: string;
    /**
     * actual measurement of weight
     */
    weight?: number;
    /**
     * timestamp of the measurement on one second precision
     */
    epoch?: number;
    /**
     * temperature
     */
    temperature?: number;
    /**
     * air pressure according to sensor
     */
    airPressure?: number;
    /**
     * Battery voltage
     */
    batteryVoltage?: number;
    /**
     * signal Strength in %
     */
    signalStrength?: number;
}

