/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Telemetry { 
    /**
     * The mac address of the scale
     */
    m?: string;
    /**
     * actual measurement of weight
     */
    w?: number;
    /**
     * timestamp of the measurement on one second precision (unix timestamp)
     */
    e?: number;
    /**
     * temperature
     */
    t?: number;
    /**
     * air pressure according to sensor
     */
    a?: number;
    /**
     * Battery voltage
     */
    b?: number;
    /**
     * signal Strength in %
     */
    s?: number;
    /**
     * longitude of the system
     */
    lo?: number;
    /**
     * latitude of the system
     */
    la?: number;
    /**
     * Humidity in percent
     */
    h?: number;
}

