/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Telemetry { 
    /**
     * The mac address of the scale; short form: m
     */
    macAddress?: string;
    /**
     * actual measurement of weight; short form: w
     */
    weight?: number;
    /**
     * timestamp of the measurement on one second precision; short form: e
     */
    epoch?: number;
    /**
     * temperature; short form: t
     */
    temperature?: number;
    /**
     * air pressure according to sensor; short form: p
     */
    airPressure?: number;
    /**
     * Battery voltage; short form: b
     */
    batteryVoltage?: number;
    /**
     * signal Strength in %; short from: s
     */
    signalStrength?: number;
    /**
     * longitude of the system; short form: lo
     */
    longitude?: number;
    /**
     * latitude of the system; short form: la
     */
    latitude?: number;
}

