/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Temperature { 
    /**
     * bhiveId to identify the data source. Might become empty in a future iteration as it\'s redundant with the query parameter.
     */
    bhiveId: string;
    /**
     * actual measurement of the temperature
     */
    temperature: number;
    /**
     * timestamp of the measurement on one second precision
     */
    epoch: number;
}

