/**
 * Queensaver API
 * Queensaver API to send in sensor data and retrieve it. It\'s also used for user management.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VarroaScanMetadata } from './varroaScanMetadata';


export interface VarroaScan { 
    /**
     * bhiveId to identify the data source. Might become empty in a future iteration as it\'s redundant with the query parameter.
     */
    bhiveId?: string;
    /**
     * URL to the image of the varroa scan
     */
    imageUrl?: string;
    /**
     * timestamp of the measurement on one second precision
     */
    epoch?: number;
    metadata?: Array<VarroaScanMetadata>;
    /**
     * the number of varroa mites in a scan
     */
    mites?: number;
    /**
     * the scanned image data in binary format. this is used internally and won\'t surface at the API server (any data will be ignored).
     */
    scan?: string;
}

