//
//Queensaver API
//
//Queensaver API to send in sensor data and retrieve it. It's also used for user management.
//
//The version of the OpenAPI document: 0.0.1
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: models/stand.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A stand can have many hives. However, when sending POST or PUT requests you can only update the stand metadata, any hives attached to this array will be ignored. You will have to do the /hives API call instead to create / update hives with the correct stand UUID. This array will only be populated with GET requests.
	Hives []*Hive `protobuf:"bytes,1,rep,name=hives,proto3" json:"hives,omitempty"`
	// Name of the stand. Can be chosen by the user. A stand is a collection of bee hives.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// latitude of the stand
	Latitude float64 `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	// longitude of the stand
	Longitude float64 `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	// HTTP response code. Used for internal purposes, will be let out at the API level.
	HttpReponseCode int32 `protobuf:"varint,6,opt,name=httpReponseCode,proto3" json:"httpReponseCode,omitempty"`
	// Epoch when the data was last updated. This will be set internally, no need to add this with PUT or POST calls.
	Epoch int64 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (x *Stand) Reset() {
	*x = Stand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_stand_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Stand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stand) ProtoMessage() {}

func (x *Stand) ProtoReflect() protoreflect.Message {
	mi := &file_models_stand_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stand.ProtoReflect.Descriptor instead.
func (*Stand) Descriptor() ([]byte, []int) {
	return file_models_stand_proto_rawDescGZIP(), []int{0}
}

func (x *Stand) GetHives() []*Hive {
	if x != nil {
		return x.Hives
	}
	return nil
}

func (x *Stand) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stand) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Stand) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Stand) GetHttpReponseCode() int32 {
	if x != nil {
		return x.HttpReponseCode
	}
	return 0
}

func (x *Stand) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_models_stand_proto protoreflect.FileDescriptor

var file_models_stand_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x1a, 0x11, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x68, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xba, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x05, 0x68, 0x69,
	0x76, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x70, 0x65, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x48, 0x69, 0x76, 0x65, 0x52, 0x05, 0x68, 0x69, 0x76, 0x65, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x28, 0x0a,
	0x0f, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x68, 0x74, 0x74, 0x70, 0x52, 0x65, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x65, 0x70, 0x6f, 0x63, 0x68, 0x50, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_stand_proto_rawDescOnce sync.Once
	file_models_stand_proto_rawDescData = file_models_stand_proto_rawDesc
)

func file_models_stand_proto_rawDescGZIP() []byte {
	file_models_stand_proto_rawDescOnce.Do(func() {
		file_models_stand_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_stand_proto_rawDescData)
	})
	return file_models_stand_proto_rawDescData
}

var file_models_stand_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_stand_proto_goTypes = []interface{}{
	(*Stand)(nil), // 0: openapi.Stand
	(*Hive)(nil),  // 1: openapi.Hive
}
var file_models_stand_proto_depIdxs = []int32{
	1, // 0: openapi.Stand.hives:type_name -> openapi.Hive
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_models_stand_proto_init() }
func file_models_stand_proto_init() {
	if File_models_stand_proto != nil {
		return
	}
	file_models_hive_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_models_stand_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Stand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_stand_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_stand_proto_goTypes,
		DependencyIndexes: file_models_stand_proto_depIdxs,
		MessageInfos:      file_models_stand_proto_msgTypes,
	}.Build()
	File_models_stand_proto = out.File
	file_models_stand_proto_rawDesc = nil
	file_models_stand_proto_goTypes = nil
	file_models_stand_proto_depIdxs = nil
}
