//
//Queensaver API
//
//Queensaver API to send in sensor data and retrieve it. It's also used for user management.
//
//The version of the OpenAPI document: 0.0.1
//
//Generated by OpenAPI Generator: https://openapi-generator.tech

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: models/varroa_scan_metadata.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VarroaScanMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// classification of the object - that could be a bee_wing, mite, wax_platelets, wax_moth_droppings, etc...
	Class string `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	// how confident the AI is regarding the result
	Confidence float64 `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// center of the object on the x axis
	XCenter float64 `protobuf:"fixed64,3,opt,name=xCenter,proto3" json:"xCenter,omitempty"`
	// center of the object on the y axis
	YCenter float64 `protobuf:"fixed64,4,opt,name=yCenter,proto3" json:"yCenter,omitempty"`
	// width of the object
	Width float64 `protobuf:"fixed64,5,opt,name=width,proto3" json:"width,omitempty"`
	// height of the object
	Height float64 `protobuf:"fixed64,6,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *VarroaScanMetadata) Reset() {
	*x = VarroaScanMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_varroa_scan_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarroaScanMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarroaScanMetadata) ProtoMessage() {}

func (x *VarroaScanMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_models_varroa_scan_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarroaScanMetadata.ProtoReflect.Descriptor instead.
func (*VarroaScanMetadata) Descriptor() ([]byte, []int) {
	return file_models_varroa_scan_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *VarroaScanMetadata) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *VarroaScanMetadata) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *VarroaScanMetadata) GetXCenter() float64 {
	if x != nil {
		return x.XCenter
	}
	return 0
}

func (x *VarroaScanMetadata) GetYCenter() float64 {
	if x != nil {
		return x.YCenter
	}
	return 0
}

func (x *VarroaScanMetadata) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VarroaScanMetadata) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_models_varroa_scan_metadata_proto protoreflect.FileDescriptor

var file_models_varroa_scan_metadata_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x61, 0x72, 0x72, 0x6f, 0x61, 0x5f,
	0x73, 0x63, 0x61, 0x6e, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x70, 0x65, 0x6e, 0x61, 0x70, 0x69, 0x22, 0xac, 0x01, 0x0a,
	0x12, 0x56, 0x61, 0x72, 0x72, 0x6f, 0x61, 0x53, 0x63, 0x61, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x64, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x78, 0x43, 0x65,
	0x6e, 0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x78, 0x43, 0x65, 0x6e,
	0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x79, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x79, 0x43, 0x65, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a,
	0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_models_varroa_scan_metadata_proto_rawDescOnce sync.Once
	file_models_varroa_scan_metadata_proto_rawDescData = file_models_varroa_scan_metadata_proto_rawDesc
)

func file_models_varroa_scan_metadata_proto_rawDescGZIP() []byte {
	file_models_varroa_scan_metadata_proto_rawDescOnce.Do(func() {
		file_models_varroa_scan_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_varroa_scan_metadata_proto_rawDescData)
	})
	return file_models_varroa_scan_metadata_proto_rawDescData
}

var file_models_varroa_scan_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_models_varroa_scan_metadata_proto_goTypes = []interface{}{
	(*VarroaScanMetadata)(nil), // 0: openapi.VarroaScanMetadata
}
var file_models_varroa_scan_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_varroa_scan_metadata_proto_init() }
func file_models_varroa_scan_metadata_proto_init() {
	if File_models_varroa_scan_metadata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_varroa_scan_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarroaScanMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_varroa_scan_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_varroa_scan_metadata_proto_goTypes,
		DependencyIndexes: file_models_varroa_scan_metadata_proto_depIdxs,
		MessageInfos:      file_models_varroa_scan_metadata_proto_msgTypes,
	}.Build()
	File_models_varroa_scan_metadata_proto = out.File
	file_models_varroa_scan_metadata_proto_rawDesc = nil
	file_models_varroa_scan_metadata_proto_goTypes = nil
	file_models_varroa_scan_metadata_proto_depIdxs = nil
}
